services:
  dragon-dns:
    build: .
    container_name: ddns
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - MACHINE_ID=${MACHINE_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - CACHE_EXPIRATION=${CACHE_EXPIRATION}
